# Matrix Multiplication
## Rules
1. When A is m * n matrix, we can multiply A with a vector of size nx1
    - A's row count should be equal to V's column count
2. AxB __!=__ BxA in matrix multiplication

In [27]:
import numpy as np
A = np.array([[1,2],[0,1],[2,3]])
V = np.array([[2],[6]])
print(f"\nA matrix\n",A)
print(f"\nV matrix\n",V)
print("\nMatrix multiplication")
print(np.dot(A,V)) #matrix multiplication



A matrix
 [[1 2]
 [0 1]
 [2 3]]

V matrix
 [[2]
 [6]]

Matrix multiplication
[[14]
 [ 6]
 [22]]


In [28]:
A = np.array([[1,2],[0,1],[2,3]])
V = np.array([[2,7],[6,3]])
print(f"\nA matrix\n",A)
print(f"\nV matrix\n",V)
print("\nMatrix multiplication")
print(np.dot(A,V)) #matrix multiplication


A matrix
 [[1 2]
 [0 1]
 [2 3]]

V matrix
 [[2 7]
 [6 3]]

Matrix multiplication
[[14 13]
 [ 6  3]
 [22 23]]


# Rule 2 AxB __!=__ BxA in matrix multiplication

In [29]:
A = np.array([[1,2],[0,1]])
V = np.array([[2,7],[6,3]])
print(f"\nA matrix\n",A)
print(f"\nV matrix\n",V)
print("\nMatrix multiplication AxV")
print(np.dot(A,V)) #matrix multiplication
print("\nMatrix multiplication VxA")
print(np.dot(V,A)) #matrix multiplication


A matrix
 [[1 2]
 [0 1]]

V matrix
 [[2 7]
 [6 3]]

Matrix multiplication AxV
[[14 13]
 [ 6  3]]

Matrix multiplication VxA
[[ 2 11]
 [ 6 15]]


## Conditions where AxV == VxA

In [36]:
A = np.array([[1,0],[0,1]])
V = np.array([[0,1],[1,0]])
print(f"\nA matrix\n",A)
print(f"\nV matrix\n",V)
print("\nMatrix multiplication AxV")
print(np.dot(A,V)) #matrix multiplication
print("\nMatrix multiplication VxA")
print(np.dot(V,A)) #matrix multiplication


A matrix
 [[1 0]
 [0 1]]

V matrix
 [[0 1]
 [1 0]]

Matrix multiplication AxV
[[0 1]
 [1 0]]

Matrix multiplication VxA
[[0 1]
 [1 0]]


# Question: Can we express linear regression in matrix-vector format?

In [38]:
import matplotlib.pyplot as plt

# Running Distance in Mile
x = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])

# Water Drinks in Litre
y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])
#We can obtain the prediction vector as the following:

w1 = 0.25163494 
w0 = 0.79880123 
y_pred = [w1*i + w0 for i in x]
print(y_pred)

[1.629196532, 1.905994966, 2.1827934, 2.4872716774, 2.5426313642, 1.84761565992, 3.25953930826, 2.3544084290800003, 2.7087104245999996, 1.34409414498, 2.57081447748, 3.51419386754, 2.13573766622, 2.81112584518, 2.2215451807599997, 3.1314571237999997, 1.578869544]


In [40]:
# print(np.transpose([x]))
# Concatenate two matrix column-wise 
X = np.concatenate((np.transpose([x]), np.ones((len(x), 1))), axis=1)
print(X)

[[ 3.3    1.   ]
 [ 4.4    1.   ]
 [ 5.5    1.   ]
 [ 6.71   1.   ]
 [ 6.93   1.   ]
 [ 4.168  1.   ]
 [ 9.779  1.   ]
 [ 6.182  1.   ]
 [ 7.59   1.   ]
 [ 2.167  1.   ]
 [ 7.042  1.   ]
 [10.791  1.   ]
 [ 5.313  1.   ]
 [ 7.997  1.   ]
 [ 5.654  1.   ]
 [ 9.27   1.   ]
 [ 3.1    1.   ]]


In [43]:
# Another way
print(v_ones)
X = np.array([x, np.ones((1, len(x)))])
print(X)
w = np.array([w1, w0])
np.dot(w, X)


NameError: name 'v_ones' is not defined

# Transpose array.T

In [48]:
A = np.array([[1,2],[0,1],[2,3]])
V = np.array([[2],[6]])
print(A.T) #.T transpose a matrix

[[1 0 2]
 [2 1 3]]


# Norm

In [49]:
from numpy import linalg as LA
v = np.array([3, 4])
LA.norm(v)

5.0

In [51]:

V = np.array([3, 4])
np.sqrt(np.dot(V,V.T))

5.0

In [52]:
# What is the distance between two vector u and v

In [59]:
u = np.array([1,1])
v = np.array([2,2])
r = np.array([3,8])
print(f"u-v =",u-v)
print(f"norm(u-v) =",LA.norm(u-v))
print(f"norm(u-r) =",LA.norm(u-r))
print(f"norm(v-r) =",LA.norm(v-r))

u-v = [-1 -1]
norm(u-v) = 1.4142135623730951
norm(u-r) = 7.280109889280518
norm(v-r) = 6.082762530298219
